sudo: required
services:
  - docker

# before_install:
#   - docker build -t yurii/frontend -f frontend/Dockerfile.dev .

script:
  - echo "test"

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "geo-pins"
  env: "GeoPins-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-064693154869"
  bucket_path: "geo-pins"
  on:
    branch: master
  edge: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
