sudo: required
services:
  - docker

stages:
  - test
  - name: deploy-images
    if: branch = master
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - docker build -t yurr92/frontend -f ./frontend/Dockerfile.dev ./frontend
        - docker run yurr92/frontend yarn test -- --coverage
    - stage: deploy-images
      script:
        - docker build -t yurr92/frontend ./frontend
        - docker build -t yurr92/backend ./backend
        - docker build -t yurr92/nginx ./nginx
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push yurr92/frontend
        - docker push yurr92/backend
        - docker push yurr92/nginx
    - stage: deploy
      script: skip
      deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "geoPins"
        env: "Geopins-env"
        bucket_name: "elasticbeanstalk-us-east-2-064693154869"
        bucket_path: "geoPins"
        on:
          branch: master
        edge: true
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
