version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /usr/app/node_modules
      - ./backend/src:/usr/app/src
    environment:
      - RDS_HOSTNAME=db
      - RDS_PORT=5432
      - RDS_USERNAME=postgres
      - RDS_PASSWORD=test
      - SECRET=sdfsdf3ewfs
  frontend:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - ./frontend/src:/usr/app/src
    environment:
      - REACT_APP_MAP_BOX_TOKEN=pk.eyJ1IjoieXJyOTIiLCJhIjoiY2swamV2eTRrMDk0bTNucG5xdGE3YnFmYiJ9.wVtCsbkHfBmgj1mhwu8_1g
