version: "3"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - /usr/app/node_modules
      - ./backend/src:/usr/app/src
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - ./frontend/src:/usr/app/src
