version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - /usr/app/node_modules
      - ./backend/src:/usr/app/src
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USERNAME=postgres
      - PG_PASSWORD=test
      - SECRET=sdfsdfwer23rwefsf
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - ./frontend/src:/usr/app/src
    environment:
      - REACT_APP_MAP_BOX_TOKEN=pk.eyJ1IjoieXJyOTIiLCJhIjoiY2swamV2eTRrMDk0bTNucG5xdGE3YnFmYiJ9.wVtCsbkHfBmgj1mhwu8_1g
