input CreatePinInput {
  pinId: String!
  text: String!
  placeName: String!
  center: [Float]!
  placeType: String!
}

type Mutation {
  CreatePin(input: CreatePinInput!): Pin
  DeletePin(input: DeletePinInput!): [Pin]
  SignIn(input: SignInUser!): Token!
  SignUp(input: SignUpUser!): Token!
}

input DeletePinInput {
  pinId: String!
}

input GetPinInput {
  pinId: String!
}

type Query {
  GetPin(input: GetPinInput!): Pin
  GetPins: [Pin]!
  CurrentUser: User
}

type Comment {
  text: String!
  createdAt: String
  author: User
  pin: Pin
}

type Pin {
  id: String!
  pinId: String!
  text: String!
  createdAt: String!
  placeName: String!
  placeType: String!
  center: [Float!]!
  author: User
  comments: [Comment]
}

type User {
  id: ID!
  login: String!
  email: String!
  password: String!
  image: String
  pins: [Pin]
  createdAt: String
  updatedAt: String
}

type Token {
  token: String
}

input SignInUser {
  login: String!
  password: String!
}

input SignUpUser {
  login: String!
  email: String!
  password: String!
  image: String
}
